### ISSUE TITLE
error in redmine 5.1.2

### ISSUE THREAD

**Issue by ashrafalzyoud** [two-pack/redmine_xlsx_format_issue_exporter#101]
```
ActionView::Template::Error (undefined method `>' for nil:NilClass):
    18:         <% end %>
    19:       </fieldset>
    20:     <% end %>
    21:     <% if @issue_count > Setting.issues_export_limit.to_i %>
    22:     <p class="icon icon-warning">
    23:       <%= l(:setting_issues_export_limit) %>: <%= Setting.issues_export_limit.to_i %>
    24:     </p>
  
plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb:21
plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb:5
plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/view_layouts_base_body_bottom_hook.rb:26:in `view_layouts_base_body_bottom'
lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:66:in `each'
lib/redmine/hook.rb:66:in `block in call_hook'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:101:in `call_hook'
app/views/layouts/base.html.erb:121
app/controllers/issues_controller.rb:86:in `block (2 levels) in index'
app/controllers/issues_controller.rb:85:in `index'
plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/issues_controller_patch.rb:10:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
  
ActionView::Template::Error (undefined method `>' for nil:NilClass):
    18:         <% end %>
    19:       </fieldset>
    20:     <% end %>
    21:     <% if @issue_count > Setting.issues_export_limit.to_i %>
    22:     <p class="icon icon-warning">
    23:       <%= l(:setting_issues_export_limit) %>: <%= Setting.issues_export_limit.to_i %>
    24:     </p>
  
plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb:21
plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb:5
plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/view_layouts_base_body_bottom_hook.rb:26:in `view_layouts_base_body_bottom'
lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:66:in `each'
lib/redmine/hook.rb:66:in `block in call_hook'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:101:in `call_hook'
app/views/layouts/base.html.erb:121
app/controllers/issues_controller.rb:86:in `block (2 levels) in index'
app/controllers/issues_controller.rb:85:in `index'
plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/issues_controller_patch.rb:10:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by two-pack** [comment]
See below and show more details of your environment and how to reproduce it.
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/wiki/How-to-report-issue

**Comment by two-pack** [comment]
Are you setting up a query to filter issues? Please provide more details about the configuration. Also, please confirm if there are no errors when there is no filter applied.

**Comment by two-pack** [comment]
I was able to reproduce it with the following steps:
1. Open the Issues page.
2. Select "Copied from" from "Add filter".
3. Press "Apply".

And I created PR #102 for fixing it. @ashrafalzyoud , cloud you check the PR on your environment?
