### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by jaebokoh** [two-pack/redmine_xlsx_format_issue_exporter#103]
[e618b8e9-4708-46fe-b038-b79d0670f448] TypeError (no implicit conversion of nil into Array):
[e618b8e9-4708-46fe-b038-b79d0670f448]   
[e618b8e9-4708-46fe-b038-b79d0670f448] plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/xlsx_report_helper.rb:20:in `+'
[e618b8e9-4708-46fe-b038-b79d0670f448] plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/xlsx_report_helper.rb:20:in `report_to_xlsx'
[e618b8e9-4708-46fe-b038-b79d0670f448] plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/timelog_controller_patch.rb:28:in `report'

**Comment by two-pack** [comment]
According to following, please write more information,
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/wiki/How-to-report-issue

**Comment by two-pack** [comment]
Closing due to prolonged inactivity.
