### ISSUE TITLE
Error when user does not select any issue status

### ISSUE THREAD

**Issue by lublasco** [two-pack/redmine_xlsx_format_issue_exporter#15]
Hi,

thanks a lot for your plugin. It is really useful.

When the user creates a filter but forgets to select the issue status, Redmine gives a message "Status cannot be blank".

However after installing your plugin, Redmine gives an error for the same action.

This is the production.log:

```
Started GET "/redmine/projects/proyecto-x/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=%3D&f%5B%5D=tracker_id&op%5Btracker_id%5D=%3D&v%5Btracker_id%5D%5B%5D=11&f%5B%5D=&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&group_by=" for 127.0.0.1 at 2016-05-09 03:04:01 -0500
Processing by IssuesController#index as HTML
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "f"=>["status_id", "tracker_id", ""], "op"=>{"status_id"=>"=", "tracker_id"=>"="}, "v"=>{"tracker_id"=>["11"]}, "c"=>["tracker", "status", "priority", "subject", "assigned_to", "updated_on"], "group_by"=>"", "project_id"=>"proyecto-x"}
  Current user: User (id=14)
  Rendered queries/_filters.html.erb (15.6ms)
  Rendered queries/_columns.html.erb (0.0ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_view_issues_index_bottom.erb (15.6ms)
  Rendered issues/index.html.erb within layouts/base (31.2ms)
Completed 500 Internal Server Error in 62ms (ActiveRecord: 0.0ms)

ActionView::Template::Error (undefined method `>' for nil:NilClass):
    20:         <label><%= check_box_tag 'description', '1', @query.has_column?(:description) %> <%= l(:field_description) %></label>
    21:         <label><%= check_box_tag 'files', '1', false %> <%= l(:label_attachment_plural) %></label>
    22:       </p>
    23:       <% if @issue_count > Setting.issues_export_limit.to_i %>
    24:           <p class="icon icon-warning">
    25:             <%= l(:setting_issues_export_limit) %>: <%= Setting.issues_export_limit.to_i %>
    26:           </p>
  plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_view_issues_index_bottom.erb:23:in `block in _plugins_redmine_xlsx_format_issue_exporter_app_views_hooks__view_issues_index_bottom_erb__816559973_91341588'
  plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_view_issues_index_bottom.erb:14:in `_plugins_redmine_xlsx_format_issue_exporter_app_views_hooks__view_issues_index_bottom_erb__816559973_91341588'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/index.html.erb:103:in `_app_views_issues_index_html_erb___82662002_90478956'
  app/controllers/issues_controller.rb:87:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:86:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Could you please review this?
Thanks again for your help.

**Comment by two-pack** [comment]
Thanks reporting it :)
I fixed it.

**Comment by lublasco** [comment]
Tested and OK! Thanks a lot, two-pack!
