### ISSUE TITLE
Whole description stored as URL

### ISSUE THREAD

**Issue by hsychla** [two-pack/redmine_xlsx_format_issue_exporter#21]
Hi, 

I just installed your plugin and found a problem when testing around:

If the option to export the ticket description is enabled and the description starts with a URL, the plugin tries to save the whole description as a URL in Excel.

Below is an excerpt from production.log. when trying to export a list of issues including the following description:

```
http://mxtoolbox.com/domain/REDACTED/
http://mxtoolbox.com/domain/REDACTED/

REDACTED is on 2 spamlists as far as i can see.

maybe worth reading: http://www.wpsitecare.com/keep-your-email-out-of-the-spam-folder/
```

```
RuntimeError (URL 'http://mxtoolbox.com/domain/REDACTED/%20http://mxtoolbox.com/domain/REDACTED/%20%20REDACTED%20is%20on%202%20spamlists%20as%20far%20as%20i%20can%20see.%20%20%20maybe%20worth%20reading:%20http://www.wpsitecare.com/keep-your-email-out-of-the-spam-folder/' > 255 characters, it exceeds Excel's limit for URLS.):
  vendor/bundle/ruby/2.1.0/gems/write_xlsx-0.83.0/lib/write_xlsx/worksheet/hyperlink.rb:47:in `initialize'
  vendor/bundle/ruby/2.1.0/gems/write_xlsx-0.83.0/lib/write_xlsx/worksheet/hyperlink.rb:18:in `new'
  vendor/bundle/ruby/2.1.0/gems/write_xlsx-0.83.0/lib/write_xlsx/worksheet/hyperlink.rb:18:in `factory'
  vendor/bundle/ruby/2.1.0/gems/write_xlsx-0.83.0/lib/write_xlsx/worksheet.rb:2659:in `write_url'
  vendor/bundle/ruby/2.1.0/gems/write_xlsx-0.83.0/lib/write_xlsx/worksheet.rb:1782:in `write'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:104:in `write_item'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:60:in `block (2 levels) in write_item_rows'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:58:in `each'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:58:in `each_with_index'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:58:in `block in write_item_rows'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:57:in `each'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:57:in `each_with_index'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:57:in `write_item_rows'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:35:in `export_to_xlsx'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:7:in `query_to_xlsx'
  plugins/redmine_xlsx_format_issue_exporter/lib/issues_controller_patch.rb:39:in `index_with_xlsx'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:491:in `_run__813178247808932634__process_action__346673066198120408__callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/2.1.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__4500349642697755139__call__2259911332148893479__callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
  vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
  vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/configuration.rb:82:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
  vendor/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
  vendor/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by two-pack** [comment]
What is your environment(version of Redmine, ruby, this plugin, etc.) when reproduced this problem?
I tried with latest master branch on Redmine 3.3.0, but not reproduced it.

**Comment by hsychla** [comment]
Environment is old(!).

```
Environment:
  Redmine version                2.6.3.stable.14155
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.0
  redmine_agile                  1.3.8
  redmine_checklists             3.0.4
  redmine_contacts               3.4.5
  redmine_contacts_google_sync   2.0.3
  redmine_contacts_helpdesk      2.4.0
  redmine_contacts_invoices      3.3.0
  redmine_contacts_money_exchange 1.1.1
  redmine_finance                1.2.1
  redmine_ics_export             3.0.1.dev
  redmine_mentions               0.0.1
  redmine_people                 0.1.8
  redmine_products               1.1.0
  redmine_questions              0.0.5
  redmine_slack                  0.1
  redmine_tags                   2.0.1-dev
  redmine_timesheet_plugin       0.7.0
  redmine_xlsx_format_issue_exporter 0.1.2
  wiki_external_filter           0.0.2
```

We are currently setting up a new server with everything up to date but MGMT needed this plugin on the old server... 

If this does not happen on a current version, everything is fine. We can live with the (not) bug until we update.

**Comment by two-pack** [comment]
I checked on Redmine 2.3.4, ruby 2.0.0, and release version 0.1.2 of this plugin, but not reproduced it too.

I will try on Redmine 2.3.6 and ruby 2.1.2. I think this problem is occurred with some other plugins related description. 
I need more time to research...

**Comment by hsychla** [comment]
I just tried it on our fully updated new server: 

```
Started GET "/issues.xlsx?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&v%5Bstatus_id%5D%5B%5D=&sort=id%3Adesc&columns=all&description=1&files=1" for 127.0.0.1 at 2016-07-06 17:10:29 +0200
Processing by IssuesController#index as 
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "f"=>["status_id"], "op"=>{"status_id"=>"o"}, "v"=>{"status_id"=>[""]}, "sort"=>"id:desc", "columns"=>"all", "description"=>"1", "files"=>"1"}
  Current user: hsychla (id=4)
Completed 500 Internal Server Error in 1224ms (ActiveRecord: 181.1ms)

RuntimeError (URL 'http://mxtoolbox.com/domain/REDACTED/%20http://mxtoolbox.com/domain/REDACTED/%20%20REDACTED%20is%20on%202%20spamlists%20as%20far%20as%20i%20can%20see.%20%20%20maybe%20worth%20reading:%20http://www.wpsitecare.com/keep-your-email-out-of-the-spam-folder/' > 255 characters, it exceeds Excel's limit for URLS.):
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:104:in `write_item'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:60:in `block (2 levels) in write_item_rows'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:58:in `each'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:58:in `each_with_index'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:58:in `block in write_item_rows'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:57:in `each'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:57:in `each_with_index'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:57:in `write_item_rows'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:35:in `export_to_xlsx'
  plugins/redmine_xlsx_format_issue_exporter/lib/xlsx_export_helper.rb:7:in `query_to_xlsx'
  plugins/redmine_xlsx_format_issue_exporter/lib/issues_controller_patch.rb:39:in `index_with_xlsx'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

```
Environment:
  Redmine version                3.3.0.stable.15606
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.3
  redmine_agile                  1.4.1
  redmine_checklists             3.1.3
  redmine_contacts               4.0.4
  redmine_contacts_helpdesk      3.0.3
  redmine_contacts_invoices      4.1.1
  redmine_finance                2.1.0
  redmine_ics_export             3.0.1.dev
  redmine_mentions               0.0.1
  redmine_people                 1.2.0
  redmine_products               2.0.1
  redmine_questions              0.0.7
  redmine_slack                  0.1
  redmine_tags                   3.1.1
  redmine_timesheet_plugin       0.7.0
  redmine_xlsx_format_issue_exporter 0.1.2
  redmine_zenedit                0.0.2
  wiki_external_filter           0.0.3 maxrossello
```

```
*** LOCAL GEMS ***

actionmailer (4.2.6)
actionpack (4.2.6)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.2)
actionview (4.2.6)
activejob (4.2.6)
activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
acts-as-taggable-on (3.5.0)
addressable (2.4.0)
arel (6.0.3)
builder (3.2.2)
bundler (1.6.2)
coderay (1.1.1)
concurrent-ruby (1.0.2)
css_parser (1.3.7)
erubis (2.7.0)
globalid (0.3.6)
htmlentities (4.3.1)
httpclient (2.8.0)
i18n (0.7.0)
icalendar (1.5.3)
jquery-rails (3.1.4)
json (1.8.3)
liquid (2.6.3)
loofah (2.0.3)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.1)
mini_portile2 (2.1.0)
minitest (5.9.0)
net-ldap (0.12.1)
nokogiri (1.6.8)
open4 (1.3.4)
pdf-core (0.2.5)
pg (0.18.4)
pkg-config (1.1.7)
prawn (1.0.0)
protected_attributes (1.1.3)
puma (3.4.0)
rack (1.6.4)
rack-openid (1.4.2)
rack-test (0.6.3)
rails (4.2.6)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.6)
rake (11.2.2)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
redcarpet (3.3.4)
redmine_crm (0.0.22)
request_store (1.0.5)
rmagick (2.15.4)
roadie (3.1.1)
roadie-rails (1.1.1)
ruby-ole (1.2.12)
ruby-openid (2.3.0)
rubyzip (1.2.0)
spreadsheet (0.6.9)
sprockets (3.6.3)
sprockets-rails (3.1.1)
thor (0.19.1)
thread_safe (0.3.5)
ttfunk (1.1.1)
tzinfo (1.2.2)
vcard (0.2.12)
webrat (0.7.3)
wicked_pdf (1.0.6)
wkhtmltopdf-binary (0.9.9.3)
write_xlsx (0.83.0)
zip-zip (0.3)
```

**Comment by two-pack** [comment]
Can you export the issue with csv export?
And can you attatch it?

**Comment by hsychla** [comment]
Sure.

[xlsx_exporter_breaking_issue.txt](https://github.com/two-pack/redmine_xlsx_format_issue_exporter/files/351911/xlsx_exporter_breaking_issue.txt)

**Comment by two-pack** [comment]
I tried to reproduce this problem with 0.1.2 and master in following environment, but I cannot do that.

~~~
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-darwin14.0]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.17
  Mercurial                      3.0
  Git                            1.9.3
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.3
  redmine_agile                  1.4.1
  redmine_checklists             3.1.3
  redmine_contacts               4.0.4
  redmine_finance                2.1.0
  redmine_ics_export             3.0.1.dev
  redmine_mentions               0.0.1
  redmine_people                 1.2.0
  redmine_products               2.0.1
  redmine_questions              0.0.7
  redmine_slack                  0.1
  redmine_tags                   3.1.1
  redmine_timesheet_plugin       0.7.0
  redmine_xlsx_format_issue_exporter 0.1.2
  redmine_zenedit                0.0.2
  wiki_external_filter           0.0.2
~~~

Some plugins are not run on my env.

**Comment by two-pack** [comment]
I can reproduce it!

Please check description of your data on Edit box in issue page.
I prospect your data like following which has more new lines.

~~~
http://mxtoolbox.com/domain/REDACTED/
http://mxtoolbox.com/domain/REDACTED/

REDACTED is on 2 spamlists as far as i can see.


maybe worth reading: http://www.wpsitecare.com/keep-your-email-out-of-the-spam-folder/



~~~

Issue page shows above data follwoing which remove some new lines.

~~~
http://mxtoolbox.com/domain/REDACTED/
http://mxtoolbox.com/domain/REDACTED/

REDACTED is on 2 spamlists as far as i can see.

maybe worth reading: http://www.wpsitecare.com/keep-your-email-out-of-the-spam-folder/
~~~

**Comment by hsychla** [comment]
Great news but I am not sure if I follow. 

I do not see any additional newlines in the description. 
Even looking right into the DB does not show any: 

```
db=# select description from issues where id = '5823';
                                      description                                       
----------------------------------------------------------------------------------------
 http://mxtoolbox.com/domain/REDACTED/\r                                               +
 http://mxtoolbox.com/domain/REDACTED/\r                                               +
 \r                                                                                    +
 REDACTED is on 2 spamlists as far as i can see. \r                                    +
 \r                                                                                    +
 maybe worth reading: http://www.wpsitecare.com/keep-your-email-out-of-the-spam-folder/
(1 row)
```

**Comment by two-pack** [comment]
> I do not see any additional newlines in the description. 
> Even looking right into the DB does not show any:

OK, This issue is caused by your data line 4 which has a white space before \r.
I confident the cause of this issue, so start to fix it. Thanks for researching :)

**Comment by hsychla** [comment]
Ah, I see.
Thanks for fixing!

**Comment by two-pack** [comment]
I fixed it.
This error is occurred when issues have values like description which starts with http, ftp, mailto, and etc.
This case, write_xlsx gem creates hyperlink with value, but Excel's limit for URLS is 255 characters.

I fixed that the plugin NOT make hyperlink with started some keywords.

**Comment by hsychla** [comment]
We can now export all our issues.

Thank you very much!
