### ISSUE TITLE
Test is failed with "NoMethodError: undefined method `issue_count_by_group'".

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xlsx_format_issue_exporter#30]
The function of test code **IssuesControllerTest#test_index_xlsx_with_group_by** is failed with Redmine trunk.

See following Travis-CI log:
https://travis-ci.org/two-pack/redmine_xlsx_format_issue_exporter/jobs/210049475

~~~
  1) Error:
IssuesControllerTest#test_index_xlsx_with_group_by:
NoMethodError: undefined method `issue_count_by_group' for #<IssueQuery:0x000000047ee240>
    plugins/redmine_xlsx_format_issue_exporter/lib/issues_controller_patch.rb:42:in `index_with_xlsx'
    lib/redmine/sudo_mode.rb:63:in `sudo_mode'
    plugins/redmine_xlsx_format_issue_exporter/test/functional/issues_controller_test.rb:91:in `test_index_xlsx_with_group_by'
~~~

**Comment by two-pack** [comment]
Following commit of Redmine removed **issue_count_by_group**.
http://www.redmine.org/projects/redmine/repository/revisions/16387
