### ISSUE TITLE
Error on migrate with Redmine after supporting Rails 5

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xlsx_format_issue_exporter#47]
Error on migrate with Redmine after supporting Rails 5.

~~~
$ bundle exec rake db:migrate
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class
Did you mean?  to_param
~/redmine/trunk/plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/issues_controller_patch.rb:24:in `<top (required)>'
~/redmine/trunk/plugins/redmine_xlsx_format_issue_exporter/init.rb:15:in `<top (required)>'
~/redmine/trunk/lib/redmine/plugin.rb:155:in `block in load'
~/redmine/trunk/lib/redmine/plugin.rb:146:in `each'
~/redmine/trunk/lib/redmine/plugin.rb:146:in `load'
~/redmine/trunk/config/initializers/30-redmine.rb:21:in `<top (required)>'
~/redmine/trunk/config/environment.rb:14:in `<top (required)>'
~/.rbenv/versions/2.3.4/bin/bundle:22:in `load'
~/.rbenv/versions/2.3.4/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
~~~

**Comment by two-pack** [comment]
On Redmine 4, other errors are occurred.
I change this issue to fix for Redmine 4.

**Comment by two-pack** [comment]
Fixed some problem on Redmine 4.
