### ISSUE TITLE
Error when exporting users list

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xlsx_format_issue_exporter#99]
The following error is occured when exporting users list.

~~~
NoMethodError in UsersController#index
undefined method `sort_clause' for nil:NilClass

[app/helpers/sort_helper.rb:100:in `sort_clause'](http://192.168.162.120:3000/users.xlsx#)
[plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/users_controller_patch.rb:19:in `index'](http://192.168.162.120:3000/users.xlsx#)
[lib/redmine/sudo_mode.rb:61:in `sudo_mode'](http://192.168.162.120:3000/users.xlsx#)
~~~

~~~
Environment:
  Redmine version                5.0.3.devel
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux]
  Rails version                  6.1.7
  Environment                    test
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::InlineAdapter
  Mailer delivery                test
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_xlsx_format_issue_exporter 0.1.7
~~~

**Comment by two-pack** [comment]
I fixed it with #98.
